name: $PROJECT_NAME

services:
  nextjs:
    user: $UID
    hostname: nextjs-server
    container_name: nextjs-server-production
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - $NEXTJS_EXTERNAL_PORT:$NEXTJS_INTERNAL_PORT
    environment:
      - NODE_ENV=production
      - PORT=$NEXTJS_INTERNAL_PORT

volumes:
  node_modules:
